//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodPlanner.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class DietRule
    {
        public int ID { get; set; }
        public int DietID { get; set; }
        public int IngredientID { get; set; }
        public int IngredientValue { get; set; }
        public bool IngredientIsBlacklisted { get; set; }
    
        public virtual DietPreset DietPreset { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
