//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public Ingredients()
        {
            this.InventoryIngredients = new HashSet<InventoryIngredients>();
            this.RecipeIngredients = new HashSet<RecipeIngredients>();
        }
    
        public int ID { get; set; }
        public string Ingredient { get; set; }
        public string Unit { get; set; }
    
        public virtual ICollection<InventoryIngredients> InventoryIngredients { get; set; }
        public virtual ICollection<RecipeIngredients> RecipeIngredients { get; set; }
    }
}
