//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Ingredient()
        {
            this.InventoryIngredients = new HashSet<InventoryIngredient>();
            this.RecipeIngredients = new HashSet<RecipeIngredient>();
        }
    
        public int ID { get; set; }
        public string Ingredient1 { get; set; }
        public string Unit { get; set; }
    
        public virtual ICollection<InventoryIngredient> InventoryIngredients { get; set; }
        public virtual ICollection<RecipeIngredient> RecipeIngredients { get; set; }
    }
}
