//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodPlanner
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class InventoryIngredient
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int IngredientID { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual User User { get; set; }
    }
}
