//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.CookingSteps = new HashSet<CookingStep>();
            this.Meals = new HashSet<Meal>();
            this.RecipeIngredients = new HashSet<RecipeIngredient>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int Persons { get; set; }
    
        public virtual ICollection<CookingStep> CookingSteps { get; set; }
        public virtual ICollection<Meal> Meals { get; set; }
        public virtual ICollection<RecipeIngredient> RecipeIngredients { get; set; }
    }
}
