//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodPlanner.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.Meals = new ObservableCollection<Meal>();
            this.RecipeIngredients = new ObservableCollection<RecipeIngredient>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int Persons { get; set; }
        public string Image { get; set; }
        public int PreparationID { get; set; }
    
        public virtual ObservableCollection<Meal> Meals { get; set; }
        public virtual ObservableCollection<RecipeIngredient> RecipeIngredients { get; set; }
        public virtual RecipesPreparation RecipesPreparation { get; set; }
    }
}
