//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public Recipes()
        {
            this.CookingSteps = new HashSet<CookingSteps>();
            this.Meals = new HashSet<Meals>();
            this.RecipeIngredients = new HashSet<RecipeIngredients>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int Persons { get; set; }
    
        public virtual ICollection<CookingSteps> CookingSteps { get; set; }
        public virtual ICollection<Meals> Meals { get; set; }
        public virtual ICollection<RecipeIngredients> RecipeIngredients { get; set; }
    }
}
