//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodPlanner.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class User
    {
        public User()
        {
            this.InventoryIngredients = new ObservableCollection<InventoryIngredient>();
            this.Meals = new ObservableCollection<Meal>();
            this.BlacklistIngredients = new ObservableCollection<BlacklistIngredient>();
            this.StockQuantities = new ObservableCollection<StockQuantity>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int PersonsInHouseHold { get; set; }
        public int ShopAhead { get; set; }
    
        public virtual ObservableCollection<InventoryIngredient> InventoryIngredients { get; set; }
        public virtual ObservableCollection<Meal> Meals { get; set; }
        public virtual ObservableCollection<BlacklistIngredient> BlacklistIngredients { get; set; }
        public virtual ObservableCollection<StockQuantity> StockQuantities { get; set; }
    }
}
