//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.InventoryIngredients = new HashSet<InventoryIngredients>();
            this.Meals = new HashSet<Meals>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<InventoryIngredients> InventoryIngredients { get; set; }
        public virtual ICollection<Meals> Meals { get; set; }
    }
}
